# Generated by Django 3.0.3 on 2020-03-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhstats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prof_area',
            options={'ordering': ['name'], 'verbose_name': 'Профессиональная область', 'verbose_name_plural': 'Профессиональные области'},
        ),
        migrations.AlterModelOptions(
            name='prof_specs',
            options={'ordering': ['name'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'ordering': ['vac_city'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['name'], 'verbose_name': 'Ключевой навык', 'verbose_name_plural': 'Ключевые навыки'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'ordering': ['name'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='prof_area',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='prof_area',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prof_specs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='prof_specs',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='vac_city',
            field=models.CharField(default=' ', max_length=50, verbose_name='Уникальный код города'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='experience',
            field=models.IntegerField(verbose_name='Требуемый опыт'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='file_name',
            field=models.CharField(max_length=200, verbose_name='Имя файла с описанием'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='max_salary',
            field=models.FloatField(verbose_name='Максимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='min_salary',
            field=models.FloatField(verbose_name='Минимальная зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='url',
            field=models.CharField(max_length=300, verbose_name='Ссылка на объявление'),
        ),
    ]
